name: Automatic Pull Request

on:
  push:
    branches:
      - '**'  # Aciona o workflow para qualquer branch

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create a branch for PR
        id: create_branch
        run: |
          BRANCH_NAME="auto-pr-${GITHUB_SHA}"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated PR from ${{ github.head_ref }} to develop."
          body: |
            This PR was created automatically via GitHub Actions after passing all build steps.
          base: develop  # Branch base onde o PR será criado
          branch: ${{ env.BRANCH_NAME }}  # Branch de destino
          delete-branch: false
          draft: false

      - name: Display created pull request URL
        run: |
          echo "Created pull request URL: ${{ steps.create_pr.outputs.pull-request-url }}"
