name: Automatic Pull Request to Develop

on:
  push:
    branches-ignore:
      - develop  # Ignora a branch develop para não acionar o workflow nela

jobs:
  create_pr:
    runs-on: ubuntu-latest
    name: Create Pull Request to Develop

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated PR from ${{ github.head_ref }} to develop"
          body: |
            This pull request was automatically created by GitHub Actions to merge changes from branch ${{ github.head_ref }} into develop.
          base: develop  # A branch para a qual o PR será criado
          branch: auto-pr-${{ github.head_ref }}  # Nome da branch de origem do PR

      - name: Display created pull request URL
        run: |
          echo "Created pull request URL: ${{ steps.create_pr.outputs.pull-request-url }}"
