name: Maven Build and PR Creation (Maven Project)

on:
  push:
    branches-ignore:
      - 'develop'  # Ignora a branch principal para evitar criar PRs a partir dela

jobs:
  maven_build:
    runs-on: ubuntu-latest
    name: Build with Maven

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Set up Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean install

  create_pr:
    runs-on: ubuntu-latest
    name: Create Pull Request
    needs: maven_build  # Somente executa após o job de build ser concluído com sucesso

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated PR - Changes from ${{ github.head_ref }}."
          title: "Automated PR from ${{ github.head_ref }} to develop."
          body: |
            This PR was created automatically via GitHub Actions after passing all Maven build steps.
          base: develop  # Branch principal
          branch: create-pull-request/patch  # Define um nome fixo para a branch de PR
          delete-branch: false  # Não exclui a branch criada após o PR
          always-create: true  # Força a criação do PR mesmo sem mudanças

      - name: Display created pull request URL
        run: |
          echo "Created pull request URL: ${{ steps.create_pr.outputs.pull-request-url }}"
